/*
 Generated by typeshare 1.13.4
*/

/**
 * Host → webview event: a pending permission decision the UI resolves via the
 * `agent_respond_permission` command, keyed by `request_id`.
 */
export interface PermissionPrompt {
  requestId: string;
  conversationId: string;
  toolName: string;
  input: unknown;
}

/**
 * Webview → host: start (or continue) a turn in a persisted conversation with the
 * given agent. Context attachments are explicit workspace anchors such as a file
 * or a cursor position.
 */
export interface PromptRequest {
  conversationId: string;
  agentId: string;
  prompt: string;
  contextAttachments: Array<PromptContextAttachment>;
}

export interface PromptContextAttachment {
  kind: string;
  label: string;
  payload: unknown;
}

/** One streamed event for a session, rendered directly by the webview. */
export type AgentMessage =
  | {
      kind: "init";
      data: {
        model: string;
      };
    }
  | {
      kind: "text";
      data: {
        text: string;
      };
    }
  | {
      kind: "thinking";
      data: {
        text: string;
      };
    }
  | {
      kind: "toolUse";
      data: {
        id: string;
        name: string;
        input: unknown;
      };
    }
  | {
      kind: "toolResult";
      data: {
        id: string;
        content: string;
        isError: boolean;
      };
    }
  | {
      kind: "result";
      data: {
        subtype: string;
        isError: boolean;
        costUsd?: number;
      };
    }
  | {
      kind: "error";
      data: {
        code?: string;
        message: string;
      };
    }
  | { kind: "done"; data?: undefined };

/** Host → webview notification payload (`agent-message` event). */
export interface SessionMessageNotification {
  conversationId: string;
  message: AgentMessage;
}

export enum PermissionBehavior {
  Allow = "allow",
  Deny = "deny",
}
